format:
  html:
    section-divs: false
execute:
  echo: false
filters:
  - surveydown.lua
theme:
  - cosmos
  - themes/surveydown.scss
barposition: "top" # top (default), bottom, or none
barcolor: "theme" # theme (default) or a hex code
